### ISSUE TITLE
Error: Cannot find native module 'ExpoShareIntentModule', js engine: hermes

### ISSUE THREAD

**Issue by amalshaji-dev** [achorein/expo-share-intent#10]
I am new to react native, i was trying to integrate the share to app feature with the package. After installing i am getting this errro, can anyone help, Thanks

 ERROR  Error: Cannot find native module 'ExpoShareIntentModule', js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

**Comment by anton950712** [comment]
Try to create a development build first and install it on the simulator.
https://docs.expo.dev/develop/development-builds/create-a-build/

**Comment by achorein** [comment]
make sure you run the `expo prebuild --no-install` before starting the project. localy use  `expo prebuild --no-install --clean` to rebuild old native modules.
I should had more information about that in the [README](https://github.com/achorein/expo-share-intent?tab=readme-ov-file#expo-go-). You can also take a look at the expo documentation [here](https://docs.expo.dev/workflow/customizing/)

**Comment by achorein** [comment]
feel free to reopen if you still have a problem.
