### ISSUE TITLE
Expo Sentry package issue in build

### ISSUE THREAD

**Issue by davram88** [achorein/expo-share-intent#102]
**Describe the bug**
When running a development build on EAS build with sentry package installed. I get the error under Run fastlane.

Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » MagicDev/MagicDev » Build Phases » 'Upload Debug Symbols to Sentry'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script
▸ ** ARCHIVE FAILED **

When I remove expo-share-intent package and rebuild it works fine. Is there a conflict between the two packages? In app.json, the expo-share-intent plugin comes after the Sentry plugin.  Anyone know how to resolve this issue? Sentry is pretty popular with RN & Expo apps.

**To Reproduce**
Add "@sentry/react-native": "~5.22.0" to existing example and run on eas.

**Environment**
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Memory: 4.84 GB / 15.89 GB
Binaries:
  Node:
    version: 20.9.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 9.8.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.19041.0
IDEs:
  Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
  Visual Studio: Not Found
Languages:
  Java:
    version: 19.0.1
    path: C:\Program Files\Java\jdk-19.0.1\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by achorein** [comment]
surprising, I'm using Sentry with this package, what version of Expo are you using?

**Comment by davram88** [comment]
Seems to be resolved now in 2.5.2 version and expo 51
