### ISSUE TITLE
Issue sharing .csv files

### ISSUE THREAD

**Issue by BramKlapwijk** [achorein/expo-share-intent#110]
**Describe the bug**
I share a .csv file from another app. My Expo app is shown on the option list, but my Expo app did not get any data of that .txt file.
However, I tried the images file (png) and it worked.

**To Reproduce**
Share a .csv from another app

**Environment**
![Screenshot 2024-09-21 at 14 20 42](https://github.com/user-attachments/assets/591741b7-e51b-4d67-bcf8-98a0b5f10445)

**Additional context**
useShareIntent feedback:
![Screenshot 2024-09-21 at 14 18 50](https://github.com/user-attachments/assets/47139978-95be-42c0-9bab-3821354a6701)

App.json
![Screenshot 2024-09-21 at 14 23 35](https://github.com/user-attachments/assets/2a512907-cd43-486b-9efd-e3e5b814e9dd)

- expo version (ex: 49) : 51
- using firebase : no
- using static build : no
- routing : expo-router
- package version (ex: 1.2.0) : 2.3.1
- platform target : Android
- device : real device
- type: expo build

**Comment by achorein** [comment]
@BramKlapwijk fixed in v2.3.2, thanks for your feedback
