### ISSUE TITLE
When sharing an image with my application, the route handling by default takes me to +not-found.tsx in my expo-router application. 

### ISSUE THREAD

**Issue by cback97** [achorein/expo-share-intent#118]
**When sharing an image with my application, the route handling by default takes me to +not-found.tsx in my expo-router application**

**Share image to my expo-router application is the step to reproduce**

**Environment**
```
System:
  OS: macOS 14.6.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 5.68 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.8.0
    path: ~/.nvm/versions/node/v22.8.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v22.8.0/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v22.8.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- expo version (ex: 49) : 51.0.28
- using firebase : no
- using static build : no
- routing : (expo-router)
- package version (ex: 1.2.0) : 2.3.0
- platform target : iOS
- device : simulator
- type: local build

**Comment by achorein** [comment]
cannot reproduce with the example.

I think you should have something like this in your 404 page, the [example](https://github.com/achorein/expo-share-intent/blob/2b8972868932ef9309a2740e33ba6532a2d17daf/example/expo-router/app/index.tsx) uses the `Home` in `[...unmatched]` and then redirect : 

```js
  useEffect(() => {
    if (hasShareIntent) {
      // we want to handle share intent event in a specific page
      router.replace({
        pathname: "shareintent",
      });
    }
  }, [hasShareIntent]);
 ```

**Comment by nechmads** [comment]
I get the same behavior when sharing urls into the app but only on iOS, so I had to basically handle intent in two different places:
on my _layout file as well as on the not found file, and use Platform to make sure I don't handle the same intent twice.
Would love to know if there is a better solution.

**Comment by achorein** [comment]
maybe we should use the expo-router [native-intent](https://docs.expo.dev/router/advanced/native-intent/) to handle the ios deep link.
something like :

**+native-intent.tsx**
```js
import { getShareExtensionKey } from "expo-share-intent";

export function redirectSystemPath({
  path,
  initial,
}: {
  path: string;
  initial: string;
}) {
  try {
    if (initial) {
      if (path.includes(`dataUrl=${getShareExtensionKey()}`)) {
        // redirect to the ShareIntent Screen to handle data with the hook
        console.debug(
          "react-navigation[getStateFromPath] redirect to ShareIntent screen",
        );
        return "/shareintent";
      }
      return path;
    }
    return path;
  } catch {
    return "/";
  }
}

  ```

**Comment by achorein** [comment]
@cback97  @markwitt1 @nechmads I've updated the expo-router example (https://github.com/achorein/expo-share-intent/tree/main/example/expo-router/app) by deleting `[...unmatched].tsx` and using`+native-intent.ts`, so you shouldn't have any more problems!
