### ISSUE TITLE
Can't receive height/width on video (package version 1.7.0)

### ISSUE THREAD

**Issue by Audeos** [achorein/expo-share-intent#120]
I'm using expo-share-intent version 1.7.0, because of my expo version restrictions. I'm receiving the width/height of videos as null. The photos are okay. Is this fixed in 2.0+ ?

**Comment by achorein** [comment]
dimension and duration of video is only available in v2.4.1+

**Comment by achorein** [comment]
if you really need this feature in expo50 (difficulty to migrate to expo51), i can release a new 1.x version with it.

**Comment by Audeos** [comment]
That would be awesome mate.

24 Eyl 2024 Sal 20:36 tarihinde Anselme Chorein ***@***.***>
şunu yazdı:

**Comment by achorein** [comment]
@Audeos available in v1.8.0 🚀

**Comment by Audeos** [comment]
Thanks man, good work

**Comment by Audeos** [comment]
Hey again. There seems like an issue with width and height values on video. They are reversed - width value is given to height and vice versa. Can you check the code?

**Comment by achorein** [comment]
ios or android ?
we had a similar problem with images on ios that didn't take orientation into account

**Comment by Audeos** [comment]
Happens on android device on both dev and release modes, didn't check emulator. IOS is fine, again.

**Comment by achorein** [comment]
ok very well, a small correction is necessary, I'll have a look at it soon.

**Comment by achorein** [comment]
@Audeos v1.9.0 is out with the fix 🚀
