### ISSUE TITLE
Custom activation rule doesn't work with <

### ISSUE THREAD

**Issue by m1st1ck** [achorein/expo-share-intent#124]
I am trying to use custom activation but because it contains `<` it fails. 

The issue is that `plist.build(...)` correctly replaces `<` and `>` with `&lt;` and `&gt;`, but right after, there is `.replaceAll("&gt;", ">").replaceAll("&lt;", "<")`. Not sure what is the reason for that, but `< >` are not valid, since they are used for the xml tags
```
SUBQUERY (
  extensionItems,
  $extensionItem,
  SUBQUERY (
    $extensionItem.attachments,
    $attachment,
    ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.data"
  ).@count < 10
).@count >= 1
```

- package version (ex: 1.2.0) : 2.5.1
- platform target : iOS

**Comment by achorein** [comment]
🤔 Can you provide a full custom rule example to reproduce ? (In app.json format)
The replace of "&gt;" was needed when i was testing pdf custom rule.

**Comment by m1st1ck** [comment]
that is the full rule that we are currently using
```
[
        'expo-share-intent',
        {
          iosActivationRules: `
            SUBQUERY (
              extensionItems,
              $extensionItem,
              SUBQUERY (
                $extensionItem.attachments,
                $attachment,
                ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.data"
              ).@count <= 10
            ).@count >= 1
          `,
          androidIntentFilters: ['text/*', 'image/*', 'video/*', 'audio/*', 'application/*'],
          androidMultiIntentFilters: ['image/*', 'video/*', 'audio/*', 'application/*'],
        },
      ],
```
I tested with few things and it seems fine. For now I just removed the replaceAll with patch-package and created a new build, will see if some issue comes up.

**Comment by achorein** [comment]
good point, character replacement is indeed useless, I've removed it in version 2.5.2
