### ISSUE TITLE
Not working  at expo@52&ReactNative@0.76

### ISSUE THREAD

**Issue by AruSeito** [achorein/expo-share-intent#126]
**Describe the bug**

`hasShareIntent` is `false`,and  shareIntent is DEFAULT_SHARE_INTENT.

**To Reproduce**

1. Share someone from safari
2. Then this hook returned noting, and debug info

<img width="865" alt="image" src="https://github.com/user-attachments/assets/49dc7aa3-2874-4ae2-a0a4-c89859b2b764">

**Environment**
<img width="886" alt="image" src="https://github.com/user-attachments/assets/87b4d1a2-cd52-4f08-85e8-5beedfe82a1b">

**Additional context**

- expo version (ex: 49) : 52
- using firebase : no
- using static build : no 
- routing : expo-router
- package version (ex: 1.2.0) : 2.5.2
- platform target : all
- device : real device
- type: local build

**Comment by achorein** [comment]
hello !
Thanks for your feedback on Expo 52, I didn't test yet this beta version, but seems to need a few updates for the next 3.0 version :)

**Comment by AruSeito** [comment]
Hello, the information I currently have is as follows. I hope it will be helpful to you. The JavaScript did not call any native content.

<img width="605" alt="image" src="https://github.com/user-attachments/assets/7ac655b9-1d7a-44ea-97c8-1f89eadfaa0b">

The function was not executed.

**Comment by angelo-hub** [comment]
+1 if you need help on this, trying to move to 52 before i release my app, and i'm relying on this module so i had to downgrade

**Comment by usmansbk** [comment]
@achorein any update on this?

**Comment by achorein** [comment]
Unfortunately I haven't had time to have a look at this problem, but I hope to be able to do so next week.

**Comment by davidcarboni** [comment]
I'm taking a look at the release version of Expo 52 and was able to update dependencies and make a couple of changes, but it looks like there's a few other changes:

 * `ChangeEventPayload` and `StateEventPayload` are saying `does not satisfy the constraint 'never'`
 * `EventEmitter` says it doesn't take a parameter
 * `Subscription` may have been renamed to `EventSubscription`

I'm not sure what's needed for these three, but happy to offer a PR with dependency updates if that's a useful starting point?

**Comment by achorein** [comment]
sounds like a good start indeed

**Comment by davidcarboni** [comment]
Submitted: https://github.com/achorein/expo-share-intent/pull/128

**Comment by davidcarboni** [comment]
Nice, that sounds like good progress. 
I'm not familiar with this area but might get a chance to take a look and see if I can make sense of it if you've not already done it.

**Comment by achorein** [comment]
working on it !

**Comment by achorein** [comment]
I have just released a beta version on npm for testing purpose : 
- for the moment only a regression with react-navigation has been detected
- I also have some doubts about the possibility of launching an app in expo-go using the “disabled” option

you can try it : 
```
"expo-share-intent": "3.0.0-beta.0",
```

**Comment by achorein** [comment]
release 3.0.0 is out !

I've finished my tests and everything seems to be working correctly, the PR has been merged and version 3.0.0 is available!

Corrections since the beta :
- updated react-navigation example
- handle expo go client (share intent disabled)
