### ISSUE TITLE
issue build "eas-cli build -p ios"

### ISSUE THREAD

**Issue by albertonsc** [achorein/expo-share-intent#127]
$ set -o pipefail && xcodebuild -workspace ./MeuApp.xcworkspace -scheme MeuApp -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/expo/Library/Developer/Xcode/Archives/2024-11-03/MeuApp\ 2024-11-03\ 13.42.19.xcarchive archive | tee /Users/expo/workingdir/logs/MeuApp-MeuApp.log > /dev/null
62⚠️  Skipping duplicate file: ../../Library/Developer/Xcode/DerivedData/MeuApp-boesykvsrcdtofdmfbiwxcgcfodo/Build/Intermediates.noindex/ArchiveIntermediates/MeuApp/BuildProductsPath/Release-iphoneos/ShareExtension.appex
   Remove: Xcode » MeuApp/MeuApp » Build Phases » Copy Files » ShareExtension.appex

63▸ ** ARCHIVE FAILED **
64** ARCHIVE FAILED **

app.json:
{
  "expo": {
    "name": "meuApp",
    "slug": "meuApp",
    "scheme": "meuApp",
    "version": "1.0.51",
    "orientation": "default",
    "icon": "./src/assets/iconmeuApp.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./src/assets/splashNew2.png",
      "resizeMode": "contain",
      "backgroundColor": "#FFF"
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "buildNumber": "1",
      "bundleIdentifier": "org.name.meuApp",
      "bitcode": false
    },
    "android": {
      "package": "com.name.meuApp",
      "versionCode": 1,
      "adaptiveIcon": {
        "foregroundImage": "./src/assets/iconmeuApp.png",
        "backgroundColor": "#ffffff"
      },
      "permissions": ["android.permission.RECORD_AUDIO"]
    },
    "web": {
      "favicon": "./src/assets/favicon.png"
    },
    "plugins": [
      "react-native-document-scanner-plugin",
      "expo-image-picker",
      "react-native-compressor",
      "expo-build-properties",
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 34,
            "targetSdkVersion": 34,
            "buildToolsVersion": "34.0.0"
          }
        }
      ],
      "expo-asset",
      "expo-secure-store",
      [
        "expo-share-intent",
        {
          "iosActivationRules": {
            "NSExtensionActivationSupportsImageWithMaxCount": 10
          },
          "iosAppgroupIdentifier": "org.name.meuApp",
          "iosShareExtensionName": "meuApp",
          "androidMultiIntentFilters": ["image/*"],
          "androidIntentFilters": ["image/*", "*/*"]
        }
      ],
      [
        "expo-screen-orientation",
        {
          "initialOrientation": "DEFAULT"
        }
      ]
    ],
    "packagerOpts": {
      "config": "@expo/metro-config",
      "sourceExts": ["js", "jsx", "ts", "tsx", "svg", "gif", "png", "jpg"]
    },
    "updates": {
      "url": "https://u.xxxxx"
    },
    "extra": {
      "eas": {
        "projectId": "https://u.xxxxx"
      }
    }
  }
}

package.json:
{
  "name": "meuapp",
  "version": "1.0.4",
  "scripts": {
    "start": "expo start --dev-client",
    "start:dev": "expo start --dev-client",
    "build:android": "expo run:android",
    "build:ios": "expo run:ios",
    "web": "expo start --web",
    "apk": "eas build -p android --profile preview",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "ipa": "eas build -p ios --profile preview"
  },
  "dependencies": {
    "@expo/metro-config": "^0.18.11",
    "@expo/vector-icons": "^14.0.3",
    "@openspacelabs/react-native-zoomable-view": "^2.1.5",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.12",
    "axios": "^1.4.0",
    "axios-curlirize": "^2.0.0",
    "base-64": "^1.0.0",
    "buffer": "^6.0.3",
    "date-fns": "^2.30.0",
    "downloadjs": "^1.4.7",
    "eas-cli": "^12.6.0",
    "expo": "^51.0.38",
    "expo-application": "^5.9.1",
    "expo-asset": "~10.0.10",
    "expo-build-properties": "~0.12.5",
    "expo-dev-client": "~4.0.28",
    "expo-document-picker": "~12.0.2",
    "expo-file-system": "~17.0.1",
    "expo-image-crop": "^1.0.4",
    "expo-image-manipulator": "~12.0.5",
    "expo-image-picker": "~15.0.7",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-media-library": "~16.0.5",
    "expo-network": "~6.0.1",
    "expo-print": "~13.0.1",
    "expo-screen-orientation": "^7.0.5",
    "expo-secure-store": "~13.0.2",
    "expo-share-intent": "^2.5.2",
    "expo-sharing": "~12.0.1",
    "expo-splash-screen": "~0.27.6",
    "expo-sqlite": "~14.0.3",
    "expo-status-bar": "~1.12.1",
    "expo-updates": "~0.25.27",
    "expo-web-browser": "~13.0.3",
    "i18next": "^23.6.0",
    "intl-pluralrules": "^2.0.1",
    "jszip": "^3.10.1",
    "jwt-decode": "^4.0.0",
    "lodash": "^4.17.21",
    "lottie-react-native": "6.7.0",
    "moti": "^0.26.0",
    "patch-package": "^8.0.0",
    "pdf-lib": "^1.17.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^13.3.1",
    "react-native": "0.74",
    "react-native-blob-util": "^0.19.1",
    "react-native-compressor": "^1.8.23",
    "react-native-device-info": "^11.1.0",
    "react-native-document-picker": "^9.3.0",
    "react-native-document-scanner-plugin": "1.0.0",
    "react-native-dotenv": "^3.4.9",
    "react-native-elements": "^3.4.3",
    "react-native-fast-image": "^8.6.3",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-image-crop-picker": "^0.40.0",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-resizer": "^1.4.5",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-images-to-pdf": "^0.2.1",
    "react-native-loading-spinner-overlay": "^3.0.1",
    "react-native-modern-datepicker": "^1.0.0-beta.91",
    "react-native-pager-view": "6.3.0",
    "react-native-pdf": "^6.7.1",
    "react-native-quick-base64": "^2.1.2",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-share": "^9.4.1",
    "react-native-svg": "15.2.0",
    "react-native-svg-transformer": "^1.1.0",
    "react-native-toast-message": "^2.1.6",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "~0.19.10",
    "react-native-webview": "13.8.6",
    "react-native-zip-archive": "^6.1.0",
    "styled-components": "^6.0.5",
    "typescript": "~5.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0"
  },
  "private": true
}

**Comment by achorein** [comment]
@albertonsc can you retry with 3.0.1 ?

**Comment by achorein** [comment]
cannot reproduce, reopen if it still doesn't work
