### ISSUE TITLE
Request for additional guidance on: TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')

### ISSUE THREAD

**Issue by davidcarboni** [achorein/expo-share-intent#13]
**Describe the bug**
I am experiencing the documented issue regarding a post-install script:
`TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')`

**To Reproduce**
I am attempting to run:
`npx expo prebuild --no-install --clean`

** Environment **
give the output of the following command `npx react-native info`
info Fetching system and libraries information...
System:
  OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
  CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Memory: 4.30 GB / 15.20 GB
  Shell:
    version: 5.2.15
    path: /bin/bash
Binaries:
  Node:
    version: 18.18.0
    path: ~/.nvm/versions/node/v18.18.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v18.18.0/bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v18.18.0/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

info React Native v0.73.5 is now available (your project is running on v0.73.4).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.5
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.5
info For more info, check out "https://reactnative.dev/docs/upgrading?os=linux".

**Additional context**
I have looked at the patch file but an not sure where to apply this change (I have searched under node_modules for files containing "xcode" to see if I could patch there but I haven't found the indicated line of code.

I have also looked at the linked issue and added the suggested override to my `package.json` however I still get the error message.

I'm really pleased to have found your package as I would love to be able to share URLs to my app. Any pointers you can offer will be very much appreciated! 

- expo version (ex: ^50.0.8)
- routing : react-navigation
- package version (ex: 0.1.0)
- target : Android & iOS
- device : Android emulator, real Android and iOS
- type: local build (in preparation for expo build)

**Comment by achorein** [comment]
:wave: 

package resolution is not needed, the xcode dependency is already the latest.

the readme is not crystal clear about the require patch, can you try to follow these steps :

- copy the [patch](https://github.com/achorein/expo-share-intent/blob/main/example/basic/patches/xcode%2B3.0.1.patch) in you `patches` project directory (like example)

- reset dependencies and add `patch-package` for auto patching
```bash
rm -fr node_modules
yarn add patch-package
```

- add post-install script
```json
  "scripts": {
    ...
    "postinstall": "patch-package"
  },
```

- Reinstall dependencies and check that the applied patch is correct : 
```bash
$ yarn install
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ patch-package
patch-package 8.0.0
Applying patches...
xcode@3.0.1 ✔
✨  Done in 0.81s.
```

- run prebuild command
```bash
$ yarn expo prebuild --no-install
yarn run v1.22.19
$ /Users/anselme/project/expo-share-intent/expo-share-intent-plugin/example/basic/node_modules/.bin/expo prebuild --no-install
✔ Created native directories | reusing /android, /ios
✔ Updated package.json | no changes
⠦ Running prebuild[expo-share-intent] add ios share extension (scheme:exposhareintentexample appIdentifier:expo.modules.exposhareintent.example)
⠇ Running prebuild[expo-share-intent] add android filters (text/* image/*) and multi-filters (image/*)
» android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
✔ Finished prebuild
✨  Done in 3.94s.
```

**Comment by davidcarboni** [comment]
Success! Thank you so much for taking the time to document this.

I applied the steps as you described and have successfiully run prebuild.

Fantastic work - your package has landed at the exact time I needed this solution, I'm very grateful for what you've created.

**Comment by achorein** [comment]
Your are welcome, i also updated the README 👍

**Comment by mcnaveen** [comment]
Hi @achorein I'm doing the exact steps mentioned above and still facing issues.

```
yarn expo prebuild --no-install
yarn run v1.22.22
$ /Users/mcnaveen/Developer/shotix/node_modules/.bin/expo prebuild --no-install
✔ Created native directories | reusing /android, /ios
✔ Updated package.json | no changes
⠙ Running prebuild************ scheme shotix
✖ Prebuild failed
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
    at correctForPath (/Users/mcnaveen/Developer/shotix/node_modules/xcode/lib/pbxProject.js:1682:38)
    at correctForResourcesPath (/Users/mcnaveen/Developer/shotix/node_modules/xcode/lib/pbxProject.js:1672:12)
    at pbxProject.addResourceFile (/Users/mcnaveen/Developer/shotix/node_modules/xcode/lib/pbxProject.js:258:9)
    at /Users/mcnaveen/Developer/shotix/node_modules/expo-config-plugin-ios-share-extension/build/withShareExtensionXcodeTarget.js:37:20
    at async action (/Users/mcnaveen/Developer/shotix/node_modules/expo-config-plugin-ios-share-extension/node_modules/@expo/config-plugins/build/plugins/withMod.js:235:23)
    at async interceptingMod (/Users/mcnaveen/Developer/shotix/node_modules/expo-config-plugin-ios-share-extension/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/mcnaveen/Developer/shotix/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/Users/mcnaveen/Developer/shotix/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/Users/mcnaveen/Developer/shotix/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/Users/mcnaveen/Developer/shotix/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by findmeDevepos** [comment]
me too

**Comment by youngkyo0504** [comment]
me too

**Comment by youngkyo0504** [comment]
It is only working with Yarn. It is not working with npm.

**Comment by mcnaveen** [comment]
@youngkyo0504 It's not working with yarn either. I need to check again

**Comment by achorein** [comment]
Try to run patch-package command manually and recheck.
(Global install patch-package for test purpose)

**Comment by southkeys** [comment]
do u need patch-package in deps or can it go to devDeps

**Comment by markwitt1** [comment]
Did anyone get it to work with PNPM?

**Comment by achorein** [comment]
after some digging, you need to have `@expo/cli` package in your dependencies to allow "patch-package" to work. when globaly installed the npm cache is not updated.

**Comment by markwitt1** [comment]
Still having the same issue on v3.0.0 with expo 52 and @expo/cli installed

**Comment by detmarson** [comment]
In my case I had to save the pbxProject file as sudo

**Comment by sultanmyrza** [comment]
@achorein Side question:

Why do we need the [xcode patch](https://github.com/achorein/expo-share-intent/blob/main/example/basic/patches/xcode%2B3.0.1.patch)? Can we use expo-share-intent without the xcode patch? Do we need to wait until the expo-cli issue is fixed (https://github.com/expo/expo-cli/issues/4293), or is there another solution?

I got it working on Expo and tested on iOS/Android—everything works as expected. I was just wondering if new developers can simply do:
	•	yarn add expo-share-intent
	•	configure app.json

…and be good to go without needing the xcode patch or adding "postinstall": "patch-package", etc.

I also noticed that the folks over at [BlueSky Social](https://github.com/bluesky-social/social-app/tree/5130d19ebdb3267f58e2b6407eb5c4f95107887c/plugins/shareExtension) have it working for themselves, though they haven’t made a plugin for public use yet. I believe their app is used by many users, potentially around 1 million.

**Comment by magrinj** [comment]
> Did anyone get it to work with PNPM?

For `pnpm` you don't need to add `patch-package`, simple use the built-in patch system of `pnpm`, doc [here](https://pnpm.io/cli/patch)
Take a look on this video, in my case I've created the patch again as I'm on a mono-repo repository.

[![pnpm patch command](http://img.youtube.com/vi/0GjLqRGRbcY/0.jpg)](https://www.youtube.com/watch?v=0GjLqRGRbcY)

**Comment by JamieGoodson** [comment]
I can't get the patch to work. Unsure if it's pnpm related or not. Either way, whether I have `patch-package` installed (with the postinstall script) or not, I get this error:

```
Error: [ios.xcodeproj]: withIosXcodeprojBaseMod: [expo-share-intent] Could not add resource files to the Share Extension, please check your "patch-package" installation for xcode (see: https://github.com/achorein/expo-share-intent?tab=readme-ov-file#installation)
```

**Comment by JamieGoodson** [comment]
@magrinj I'm also using pnpm and a monorepo. What args did you use for the patch command? The docs show:

```
pnpm patch <pkg name>@<version>
```

And do I still manually need to put the patch file in `patches/xcode+3.0.1.patch`?

Thanks! 🙂

**Comment by eth0izzle** [comment]
@JamieGoodson not sure if you managed to resolve this. But for `pnpm` I added the following to my `package.json`

    "pnpm": {
        "patchedDependencies": {
            "xcode": "patches/xcode+3.0.1.patch"
        }
    },

**Comment by rohanshiva** [comment]
We had to include `xcode` in `package.json` for this to work. Thanks for working on this project!
