### ISSUE TITLE
Conflicts with @bacons/apple-targets

### ISSUE THREAD

**Issue by angelo-hub** [achorein/expo-share-intent#130]
**Describe the bug**
When using both [@bacons/apple-targets](https://github.com/EvanBacon/expo-apple-targets) and this package prebuild breaks, it seems to be something with how apple-targets thinks the ShareExtension is a target managed by apple-targets, trying to get a fix in so it's not as aggressive and allows overrides. Unsure to track the bug here or on the other repo.

**To Reproduce**
```
Run prebuild with both packages, and it will fail looking for an Info.plist, overriding this orphans the ShareViewController in the build scheme, but you can compile the application. The share intent just stops working
**Environment**
System:
  OS: macOS 14.4.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 250.28 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.13.0
    path: ~/.nvm/versions/node/v20.13.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.2
    path: ~/.nvm/versions/node/v20.13.0/bin/npm
  Watchman:
    version: 2024.10.28.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.75.4
    wanted: ^0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
  ```

**Additional context**

- expo version (ex: 49) : 51 and 52
- using firebase : yes / no
- using static build : yes / no
- routing : (ex: basic / expo-router / react-navigation)
- package version (ex: 1.2.0) : x.x.x
- platform target : Android / iOS
- device : simulator / real device
- type: local build

**Comment by achorein** [comment]
I think the problem comes from `@bacons/apple-targets`, it seems that during prebuild it believes that the ShareExtension module is the main application.

**Comment by angelo-hub** [comment]
@achorein yeah i have a patch i have working locally it seems to assume that ShareExtension is part of his package, and therefor tries to import a serperate plist for it under the assets folder

**Comment by Kasendwa** [comment]
Hi @achorein any chance you can share your patch file? I think I am struggling with these.

**Comment by achorein** [comment]
not related to this package => closed.
maybe @angelo-hub you can share your solution

**Comment by angelo-hub** [comment]
Tried to pass this along to Evan, we'll see where this goes @achorein

**Comment by julian-gargicevich** [comment]
@angelo-hub Did you ever get this to work??

**Comment by Kasendwa** [comment]
Hi @julian-gargicevich, this is what I currently use to circumvent this issue.

## Problem
The `@bacons/xcode` library has an issue with resolving file paths when working with iOS projects that have nested directory structures. The `resolveFilePath` method doesn't properly handle cases where:

1. The file reference already contains the full project root path
2. The file reference contains `/ios/` subdirectories in the path

This causes incorrect path resolution and can lead to build configuration issues.

## Solution
This patch fixes the path resolution logic by:

1. **Avoiding double root paths**: If the file reference already includes the root path, we set root to empty string
2. **Handling iOS subdirectories**: If the path contains `/ios/`, we extract the correct root and file reference parts
3. **Maintaining backward compatibility**: The original logic still works for standard cases

## Patch File
**Filename**: `@bacons+xcode+1.0.0-alpha.22.patch`

```diff
diff --git a/node_modules/@bacons/xcode/build/api/XCBuildConfiguration.js b/node_modules/@bacons/xcode/build/api/XCBuildConfiguration.js
index d8b8f7e..c48e1e9 100644
--- a/node_modules/@bacons/xcode/build/api/XCBuildConfiguration.js
+++ b/node_modules/@bacons/xcode/build/api/XCBuildConfiguration.js
@@ -48,11 +48,23 @@ class XCBuildConfiguration extends AbstractObject_1.AbstractObject {
     }
     /** @returns the resolved absolute file path for the `INFOPLIST_FILE` build setting if it exists. `null` if the setting does not exist. */
     resolveFilePath(key) {
-        const fileRef = this.resolveBuildSetting(key);
+        let fileRef = this.resolveBuildSetting(key);
+
         if (fileRef == null || typeof fileRef !== "string") {
             return null;
         }
-        const root = this.getXcodeProject().getProjectRoot();
+        let root = this.getXcodeProject().getProjectRoot();
+
+        if (fileRef.includes(root)) {
+            root = "";
+        }  
+
+        if (fileRef.includes('/ios/')) {
+            root = fileRef.split('/ios/')[0] + '/ios';
+
+            fileRef = fileRef.split('/ios/')[1];
+        }
+
         // TODO: Maybe interpolate
         // TODO: Maybe add root projectRoot, currently this is always `""` in my fixtures.
         return node_path_1.default.join(root, fileRef);
@@ -75,6 +87,7 @@ class XCBuildConfiguration extends AbstractObject_1.AbstractObject {
         const filePath = this.getInfoPlistFilePath();
         if (!filePath)
             return null;
```

**Comment by julian-gargicevich** [comment]
@Kasendwa you're an absolute legend!
