### ISSUE TITLE
[iOS] App not available in Share List (working on Android)

### ISSUE THREAD

**Issue by dalisalvador** [achorein/expo-share-intent#131]
**Describe the bug**
When sharing text on iOS (Safari), the App does not appear as an option in the Share list. It works as expected on Android

**To Reproduce**
create a fresh expo app
run it on ios
try to share text from Safari
Expo app does not show up

**Environment**
```
System:
  OS: macOS 15.1
  CPU: (12) arm64 Apple M2 Max
  Memory: 108.67 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.18.2/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman:
    version: 2024.11.11.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 23.0.1
    path: /opt/homebrew/opt/openjdk/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.2
    wanted: latest
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.2
    wanted: 0.76.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
  ```

- expo version (ex: 49) : 52.0.8
- using firebase : no
- using static build : no
- routing : expo-router
- package version (ex: 1.2.0) : 3.0.0
- platform target : iOS
- device : simulator
- type: local build

**Comment by achorein** [comment]
working for me with : 
```
"NSExtensionActivationSupportsText": true,
```

**Comment by Kasendwa** [comment]
Hi @achorein, for some reason I also have the same issue. Same profile like @dalisalvador. Expo SDK 52. Works great on Android but nothing at all on iOS. Though it builds successfully.

**Comment by achorein** [comment]
can you give your `iosActivationRules` config and the app from which you want to share ? (which type of content ?)

**Comment by Kasendwa** [comment]
@achorein I eventually figured out that the problem wasn't in this library. It's working great in a repro. So we are all good here.

**Comment by achorein** [comment]
sounds lile a problem with Expo Linking (`useLinkingURL`), make sure you use this package in the top of your app.
closing the issue for now, don't hesitate to reopen if needed.
