### ISSUE TITLE
Share Intent Causing Instant Crash on Mac

### ISSUE THREAD

**Issue by erdkodla** [achorein/expo-share-intent#132]
**Describe the bug**
Using the share intent on Mac leads to an instant crash.

**To Reproduce**
- Install the app from Test Flight
- Click on Share from any app

**Environment**
give the output of the following command `npx react-native info`

**Additional context**

- expo version (ex: 49) : 52
- using firebase : no
- using static build :  no
- routing : expo-router
- package version (ex: 1.2.0) : 1.2.0
- platform target :  iOS
- device : real device
- type: expo build

**Comment by achorein** [comment]
any debug information from the [crash log](https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs) ?

**Comment by achorein** [comment]
cannot reproduce on my side :/
don't hesitate to reopen if you have more informations
