### ISSUE TITLE
Running expo router demo results in crash on startup

### ISSUE THREAD

**Issue by belcast1** [achorein/expo-share-intent#139]
**Describe the bug**
I did a fresh install of this git repo and attempted to just run the expo-router example.  I'm getting a crash on app launch on iOS simulator.  Attached screenshot below.

**Environment**
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M2
  Memory: 415.59 MB / 24.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.0
    path: ~/.nvm/versions/node/v20.5.0/bin/node
  Yarn: Not Found
  npm:
    version: 9.8.0
    path: ~/.nvm/versions/node/v20.5.0/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

info React Native v0.76.5 is now available (your project is running on v0.76.3).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.76.5
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.76.3

**Additional context**

- expo version (ex: 49) : 52
- using firebase : yes / no
- using static build : yes / no
- routing : router
- package version (ex: 1.2.0) : x.x.x
- platform target :  iOS
- device : simulator
- type: local build / expo build

<img width="1613" alt="Screenshot 2024-12-10 at 9 15 58 PM" src="https://github.com/user-attachments/assets/c7bfe708-6a4d-450e-b7ce-302981c3e392">

**Comment by belcast1** [comment]
From looking online, this looks like it could be a me problem related to react duplicate versions and/or npm linking issues.  Would really appreciate any guidance as I am new to Expo and react native.

**Comment by belcast1** [comment]
I was able to start with a fresh expo project and get things working following the README.  Closing this.

**Comment by achorein** [comment]
@belcast1 I've just updated the expo-router example (https://github.com/achorein/expo-share-intent/tree/main/example/expo-router/app) you can take a new look ;)
