### ISSUE TITLE
[BUG] Android - Unable to get working

### ISSUE THREAD

**Issue by mickmister** [achorein/expo-share-intent#146]
**📋 Describe the bug**

Hello, I'm trying to build an app with the library, though I'm not able to get the share intent to show in other apps, such as Google Photos, which seems to work with other apps that use this library like the app [hoarder](https://github.com/hoarder-app/hoarder/blob/main/apps/mobile/app.json).

I've followed the instructions in the README and still cannot get it working. I've started a new expo project to reproduce the issue [here](https://github.com/jamtools/expo-share-intent-test). Please let me know if anything comes to mind as what could be the issue. Thanks so much.

`app.json` contents:

```json
{
  "expo": {
    "name": "expo-share-intent-test",
    "slug": "expo-share-intent-test",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "scheme": "myapp",
    "userInterfaceStyle": "automatic",
    "newArchEnabled": true,
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.myuser.exposhareintenttest"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "package": "com.myuser.exposhareintenttest"
    },
    "web": {
      "bundler": "metro",
      "output": "static",
      "favicon": "./assets/images/favicon.png"
    },
    "plugins": [
      "expo-router",
      [
        "expo-splash-screen",
        {
          "image": "./assets/images/splash-icon.png",
          "imageWidth": 200,
          "resizeMode": "contain",
          "backgroundColor": "#ffffff"
        }
      ],
      "expo-share-intent"
    ],
    "experiments": {
      "typedRoutes": true
    }
  }
}
```

**🛠️ To Reproduce**

Configure a project as described in the README

**💻 Expected Behavior**

Share intent shows in other apps

**📱 Screenshots or Videos**

**⚙️ Environment Details**

Please complete the following information:

- Expo SDK Version (e.g.: 51) : 52
- Package version (e.g.: 3.1.1) : 3.1.1
- Platform target : Android
- Routing :  expo-router
- Using firebase : yes / no: No
- Using static build : yes / no: Not sure
- Device : real device
- Type: local build / expo eas build: I've tried both

For build issue give the output of the following command `npx react-native info`

```
System:
  OS: macOS 15.1.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 200.81 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/Library/Caches/fnm_multishells/9432_1734231910363/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: ~/Library/Caches/fnm_multishells/9432_1734231910363/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "34"
      - "35"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 32.0.0
      - 34.0.0
      - 35.0.0
    System Images:
      - android-29 | ARM 64 v8a
      - android-29 | Intel x86 Atom
      - android-29 | Intel x86 Atom_64
      - android-29 | Google Play ARM 64 v8a
      - android-29 | Google Play Intel x86 Atom
      - android-29 | Google Play Intel x86 Atom_64
      - android-30 | Google APIs ARM 64 v8a
      - android-32 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2020.3 AI-203.7717.56.2031.7935034
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  Ruby:
    version: 3.3.6
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.3
    wanted: ^15.1.3
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.5
    wanted: 0.76.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

**📄 Logs**
If possible, paste any relevant logs here (use triple backticks for formatting):

```shell
 (NOBRIDGE) LOG  hasShareIntent false
 (NOBRIDGE) DEBUG  expoShareIntent[scheme] from expoConfig: myapp
 (NOBRIDGE) DEBUG  useShareIntent[mount] myapp {"debug": true}
 (NOBRIDGE) DEBUG  useShareIntent[refresh] com.myuser.exposhareintenttest://expo-development-client/?url=http%3A%2F%2F192.168.0.182%3A8082
 (NOBRIDGE) DEBUG  expoShareIntent[scheme] from expoConfig: myapp
 (NOBRIDGE) LOG  hasShareIntent false
 (NOBRIDGE) LOG  hasShareIntent false
 (NOBRIDGE) DEBUG  useShareIntent[to-background] reset intent
 (NOBRIDGE) DEBUG  expoShareIntent[scheme] from expoConfig: myapp
```

**Comment by achorein** [comment]
Hello,

You are using the default configuration of this package, in you par json you have : 
```js
plugins: [
  "expo-share-intent"
]
```

For image handling, you need to add some configuration, here is an example for images only :
```js
  "plugins": [
      [
        "expo-share-intent",
        {
          "iosActivationRules": {
            "NSExtensionActivationSupportsImageWithMaxCount": 1,
          },
          "androidIntentFilters": ["text/*", "image/*"]
        }
      ],
  ],
  ```

**Comment by mickmister** [comment]
@achorein Thank you! The issue is solved. I want to say a few things:

- My use case is actually for audio files (which are working now after changing some settings). I mainly used the Google Photos example because that is currently working with the example app I mentioned "hoarder". 
- I had tried `audio/*` and `*/*` (together and in isolation) before, and it turns out the issue is my voice memo app apparently is sharing as multi-file, even if only one file is being shared. So including `androidMultiIntentFilters` solved that issue.
- Also, something I didn't know until now is if I change the `androidIntentFilters` or `androidMultiIntentFilters`, I need to run `expo prebuild` again for those to take effect. I'm fairly new to expo/RN so still learning these sort of things.

I have a followup question for you: When a file is shared with the app using this library, is that file forever shared with app? Meaning, is the file url provided always going to work, or should the app copy it to its own file store for safekeeping? I imagine this may differ between android and ios. There are tradeoffs such as duplicate storage, but it's important that the file stays around in my case. Of course if the source file is deleted, then this app would no longer have access to the file, unless it was explicitly copied to a new location.

Thanks for this amazing library :100:
