### ISSUE TITLE
Incompatibility with @react-native-google-signin/google-signin

### ISSUE THREAD

**Issue by huhulacolle** [achorein/expo-share-intent#35]
**Describe the bug**

Hello,
there seems to be an incompatibility between the expo-share-intent package and @react-native-google-signin/google-signin, if both are installed, the expo-share-intent package works fine, but on iOS if you try to use the google sign in package, it crashes the app with the following error message: ERROR Your app just crashed. See the error below.
NSInvalidArgumentException: You must specify |clientID| in |GIDConfiguration

**To Reproduce**

install both packages according to their respective docs

** Environment **
give the output of the following command `npx react-native info`

System:
  OS: Windows 11 10.0.22631
  CPU: "(16) x64 AMD Ryzen 7 5800H with Radeon Graphics         "
  Memory: 5.76 GB / 15.34 GB
Binaries:
  Node:
    version: 20.11.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-232.10227.8.2321.11479570
  Visual Studio: Not Found
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Additional context**

- expo version 50
- routing : react-navigation
- package version (ex: 0.1.0)
- target : iOS
- device : real device
- type: expo build

**Comment by achorein** [comment]
this is a known issue in the previous demo https://github.com/achorein/expo-share-intent-demo/issues/19, there is some work to be done on the subject

**Comment by achorein** [comment]
@huhulacolle do you use firebase ?
did you configure GoogleSignIn with iosClientId ?
```js
GoogleSignin.configure({
  iosClientId:
    "xxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
});
```

**Comment by huhulacolle** [comment]
@achorein 
I use Google API
everything is well configured, I managed to fix the crash problem, I entered the iOS url schema in the infoplist rather than in the plugin config. 

```json
"ios": {
      "infoPlist": {
        "CFBundleURLTypes": [
          {
            "CFBundleURLSchemes": [
              "com.googleusercontent.apps.647537853682-0omdac08g4lsj26prhk1lal0l88jm7l9"
            ]
          }
        ]
      }
}
```
however, now that the google sign in package is working, when I try to share a text on the app, it no longer redirects to the app

**Comment by achorein** [comment]
The new PR aim to check this problem.

When we configure a custom scheme (CFBundleURLSchemes) the original app scheme is deleted and must be manually reassigned :

```json
 "scheme": "exposhareintentexample",
 "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "expo.modules.exposhareintent.example",
      "infoPlist": {
        "CFBundleURLTypes": [
          {
            "CFBundleURLSchemes": [
              "com.googleusercontent.apps.xxxxxxxx-xxxxxxxxx",
              "exposhareintentexample"
            ]
          }
        ]
      }
    },
```

expo show a warning on prebuild phase for that :
```
» ios: scheme: "ios.infoPlist.CFBundleURLTypes" is set in the config. Ignoring abstract property "scheme": exposhareintentexample
```

**Comment by achorein** [comment]
compatibilty check added in v1.2.1
[README](https://github.com/achorein/expo-share-intent?tab=readme-ov-file#google-signin-and-cfbundleurlschemes) updated
