### ISSUE TITLE
MacOS share extension called "Share Extension" instead of app name

### ISSUE THREAD

**Issue by joshmohrer** [achorein/expo-share-intent#39]
This seems to only happen on MacOS - on iOS its named as expected.

![2024-04-01_15 59@2x copy](https://github.com/achorein/expo-share-intent/assets/440810/b2607bcc-a5ad-485a-93e4-ca34787b16b0)

Not sure if I missed a setting.

**Comment by achorein** [comment]
I've never tested it on MacOS, but I'm sure there's a configuration for that.
but that's not really the target of this package. Do you really use react native on the desktop, or it's just a compatibility matter as users can now do it ?

**Comment by RobinHeidenis** [comment]
Are you building with EAS? In my app.json I have the following entry:
```json
"eas": {
  "build": {
    "experimental": {
      "ios": {
        "appExtensions": [
          {
            "targetName": "ShareExtension",
            "bundleIdentifier": "com.robinheidenis.hephaestus.share-extension",
            "entitlements": {
              "com.apple.security.application-groups": [
                "group.com.robinheidenis.hephaestus"
              ]
            }
          },
          {
            "targetName": "ShareExtension",
            "bundleIdentifier": "com.robinheidenis.hephaestus.share-extension"
          }
        ]
      }
    }
  },
  "projectId": "xxx"
}
 ```

Perhaps changing the name here from ShareExtension to something else might help? I don't have an IOS device, so I can't test it myself

**Comment by joshmohrer** [comment]
@achorein not MacOS exactly, I think technically an iPad OS with MacOS support.  Some users do it, but this is not that important to me. 

@RobinHeidenis  I do use EAS but my understanding is that we should ommit what you've included as build, leaving it as 

```
 "extra": {
      "eas": {
        "projectId": "xxx"
      }
   },
```
for me. 
 I dont recall from where I got that idea, but it seems to work.

**Comment by achorein** [comment]
the `eas.build.experimental` have to be removed, this is mention in the [FAQ](https://github.com/achorein/expo-share-intent?tab=readme-ov-file#ios-extension-target) in the related issue :)

@joshmohrer for your problem in macOS share menu, can you try to edit the generated `ios/ShareExtension/ShareExtension-Info.plist` with this ?
```xml
<key>CFBundleDisplayName</key>
<string>TESTNAME Share Extension</string>
```

**Comment by achorein** [comment]
@joshmohrer do you know how to test this share menu in local ? without an eas build

**Comment by joshmohrer** [comment]
I think so -- but can I launch the ipad version of the app as a MacOS app via Expo Go or development build? I'm not sure you can?

**Comment by achorein** [comment]
it cannot be tested without shipping a version on test flight :/

**Comment by achorein** [comment]
@joshmohrer can you try with this patch in your `patches/` directory for install script ? 
[expo-share-intent+1.4.0.patch](https://github.com/achorein/expo-share-intent/files/14956392/expo-share-intent%2B1.4.0.patch)

**Comment by joshmohrer** [comment]
Will do @achorein -- do I need to do this if im using 1.4.1 already?

**Comment by joshmohrer** [comment]
Or perhaps I should roll back to 1.4.0?
```

  Info:
    Patch file: patches/expo-share-intent+1.4.0.patch
    Patch was made for version: 1.4.0
    Installed version: 1.4.1

---
patch-package finished with 1 error(s).
```

**Comment by achorein** [comment]
1.4.1 does not include this change, so yes for testing purpose rollback to 1.4.0.

**Comment by achorein** [comment]
v2.1.1 includes an attempted correction but has not been tested in real conditions
