### ISSUE TITLE
Integration of Expo Share Intent with iOS Context Menu

### ISSUE THREAD

**Issue by obender** [achorein/expo-share-intent#47]
**Description:**
Enhance the expo-share-intent library by integrating it with the iOS context menu to allow users to share content directly through the context menu options. This feature would provide a native iOS sharing experience within the context of the application using the library.

**Benefits:**

Streamlines the sharing process for iOS users.
Provides a native and intuitive sharing experience on iOS devices.
Expands the utility of the expo-share-intent library for developers targeting iOS users.
This integration aims to leverage the standard iOS user interface for content sharing, making it easily adoptable and familiar to end-users.

![image](https://github.com/achorein/expo-share-intent/assets/165257/7f62f493-898e-4254-82a9-d3860709e1d4)

**Comment by obender** [comment]
@achorein We would like to sponsor this feature.

**Comment by achorein** [comment]
Sounds good, I can add this on my TODO 👍

**Comment by obender** [comment]
@achorein DO you need anything from our side?  feel free to contact me at hi@joinsafedeal.com

**Comment by achorein** [comment]
@obender I just need more information on the different use cases.
The contextual menu is different for each application, so a good start is probably to integrate the contextual menu into Safari or the photo gallery as a first step.
I need to do some research on how to manage this, it's going to take me some time.

**Comment by obender** [comment]
@achorein I belive that it's good to start with some that are common to Android and iOS

**Comment by achorein** [comment]
@obender After some research, I finally decided not to implement this kind of functionality. Even if it sounds interesting, the implementation is too specific for each use case and would require a separate project.
