### ISSUE TITLE
Text with double quotes on iOS results in JSON parsing error

### ISSUE THREAD

**Issue by jaronheard** [achorein/expo-share-intent#55]
**Describe the bug**
Double quotes in text results in a JSON parsing error for iOS. Seems to work fine on Android.

Example output:
 DEBUG  useShareIntent[active] refresh intent
 DEBUG  useShareIntent[refresh] exposhareintentexample://dataUrl=exposhareintentexampleShareKey#text
 DEBUG  expoShareIntent[scheme] from expoConfig: exposhareintentexample
 DEBUG  useShareIntent[onChange] {"value": "{ \"text\": \"Join Ashley Yang-Thompson for a reading from her book \"The Pedagogical Philosophy of Ash Yang-Thompson \", \"type\": \"text\" }"}
 ERROR  useShareIntent[onChange] [SyntaxError: JSON Parse error: Unexpected character: T]

**To Reproduce**
Start basic example, then share text containing double quotes.

**Environment**
info Fetching system and libraries information...
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 386.61 MB / 32.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 18.18.0
    path: ~/Library/Caches/fnm_multishells/52115_1713760896606/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.19.2
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.04.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.1 AI-211.7628.21.2111.8193401
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Additional context**

- expo version (ex: 49) : 50
- using firebase : no
- using static build : no
- routing : basic
- package version (ex: 1.2.0) : 1.5.0
- platform target : iOS
- device : simulator
- type: expo build

**Comment by achorein** [comment]
@jaronheard thanks for your feedback, it fixed in v1.5.1 🎉

**Comment by jaronheard** [comment]
@achorein thanks for the quick fix and the cool library!
