### ISSUE TITLE
Share extension gets stuck intermittently 

### ISSUE THREAD

**Issue by simonsturge** [achorein/expo-share-intent#63]
**Describe the bug**
If you share the same content multiple times the extension can sometimes get stuck ([see video](https://drive.google.com/file/d/1PMUf9IoLbojnaXyolkueIbkqFzKN4VDb/view?usp=share_link)). 

**To Reproduce**
I've reproduced this by sharing to the app, going back to Safari and trying to share the same content again. It took quite a few attempts for me to reproduce this, perhaps sharing the same content 5 or 6 times, however, I've had users reporting this issue when sharing only for a second time.

[Video is on Google drive as it's more than the 10mb limit](https://drive.google.com/file/d/1PMUf9IoLbojnaXyolkueIbkqFzKN4VDb/view?usp=share_link)

**Environment**
```
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 150.03 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10227.8.2321.11479570
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.22
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

**Comment by melnikovkolya** [comment]
I also experienced that issue

**Comment by achorein** [comment]
it's a tricky bug to reproduce in a non-deterministic context. it's going to take a long time to solve.

**Comment by achorein** [comment]
v2.4.0 enhance threading to avoid race condition, maybe related to this issue.
