### ISSUE TITLE
Example Docs dont clearly explain how to capture Sharing events into my app at the App.tsx level with React Nav

### ISSUE THREAD

**Issue by geetee24** [achorein/expo-share-intent#72]
Please give specific instrucs on how to capture incoming share event at the App.tsx level in React Nav Expo app.

**Comment by achorein** [comment]
Can you give me a little more information, do you want to retrieve the shareIntent before the application is fully loaded? 
If so, you'll have to manage everything in App.tsx and react navigation won't have access to it.

**Comment by geetee24** [comment]
I want to handle an incoming share in my app.TSX and nothing to do with
react navigation and I needed to trigger an event that I can then handle

**Comment by achorein** [comment]
the basic example handle this use case https://github.com/achorein/expo-share-intent/blob/main/example/basic/App.tsx

**Comment by geetee24** [comment]
basic example does not show how to trigger an event upon receipt of sharing
intent. It only has a <Text>

**Comment by geetee24** [comment]
my app has multiple providers too.

**Comment by achorein** [comment]
i don't understand, can you give me an example of what type of event you want to handle ?

**Comment by geetee24** [comment]
Need example of useEffect() that can trigger when an incoming share intent arrives in my app.

Not working:

 expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
 DEBUG  useShareIntent[mount] com.aaa.bbb.ccc {"debug": true, "onResetShareIntent": [Function onResetShareIntent]}
 DEBUG  useShareIntent[refresh] null
 DEBUG  useShareIntent[to-background] reset intent
 DEBUG  expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
 DEBUG  expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
 DEBUG  useShareIntent[mount] com.aaa.bbb.ccc {"debug": true, "onResetShareIntent": [Function onResetShareIntent]}
 DEBUG  useShareIntent[refresh] com.aaa.bbb.cccProtocol://dataUrl=ShareKey#text
 DEBUG  expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
 DEBUG  useShareIntent[active] refresh intent
 DEBUG  useShareIntent[refresh] com.aaa.bbb.cccProtocol://dataUrl=ShareKey#text
 DEBUG  expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
 DEBUG  useShareIntent[to-background] reset intent
 DEBUG  expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
 DEBUG  useShareIntent[active] refresh intent
 DEBUG  useShareIntent[refresh] com.aaa.bbb.cccProtocol://dataUrl=ShareKey#text
 DEBUG  expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
 
 code that is not showing incoming share text:
 
       React.useEffect ( () => {
             // loop forever
             
             if ( shareIntent.text ) {
                 Alert ( 'text', shareIntent.text );
             }
             
             if ( shareIntent.webUrl ) {
                 Alert ( 'weburl', shareIntent.webUrl );
             }
             
             if ( shareIntent.files ) {
                 Alert ( 'files', JSON.stringify( shareIntent.files ) );
             }
                          
         }, [hasShareIntent] );
         
         
         React.useEffect ( () => {
             // loop forever
             
             if ( shareIntent.text ) {
                 Alert ( 'text', shareIntent.text );
             }
             
             if ( shareIntent.webUrl ) {
                 Alert ( 'weburl', shareIntent.webUrl );
             }
             
             if ( shareIntent.files ) {
                 Alert ( 'files', JSON.stringify( shareIntent.files ) );
             }
                          
         }, [shareIntent] );
