### ISSUE TITLE
Followed docs - reset share - what do?

### ISSUE THREAD

**Issue by geetee24** [achorein/expo-share-intent#75]
resetShareIntent  - no idea what this is used for.  please explain

**Comment by achorein** [comment]
```js
  const { hasShareIntent, shareIntent, resetShareIntent, error } = useShareIntent();
  ```
when you received a share intent, `hasShareIntent` is `true` and  `shareIntent` got the intent data.
when calling `resetShareIntent` we set `hasShareIntent` to false and `shareIntent` to `null`.

it's usefull to change your UI without restarting your app or with an external state.

**Comment by geetee24** [comment]
i got the code to work.   However when I share say text from an app into my
app - i see a FLASH of a dialog box that auto disappears before my app
comes up with the shared text.

This flash dialog box is not my code.   It appears to be your code?  Is
it?   How make it not flash up?
