### ISSUE TITLE
lib is not forwarding shared intent to my app

### ISSUE THREAD

**Issue by geetee24** [achorein/expo-share-intent#76]
Need example of useEffect() that can trigger when an incoming share intent arrives in my app.

Not working:

expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
DEBUG useShareIntent[mount] com.aaa.bbb.ccc {"debug": true, "onResetShareIntent": [Function onResetShareIntent]}
DEBUG useShareIntent[refresh] null
DEBUG useShareIntent[to-background] reset intent
DEBUG expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
DEBUG expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
DEBUG useShareIntent[mount] com.aaa.bbb.ccc {"debug": true, "onResetShareIntent": [Function onResetShareIntent]}
DEBUG useShareIntent[refresh] com.aaa.bbb.cccProtocol://dataUrl=ShareKey#text
DEBUG expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
DEBUG useShareIntent[active] refresh intent
DEBUG useShareIntent[refresh] com.aaa.bbb.cccProtocol://dataUrl=ShareKey#text
DEBUG expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
DEBUG useShareIntent[to-background] reset intent
DEBUG expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc
DEBUG useShareIntent[active] refresh intent
DEBUG useShareIntent[refresh] com.aaa.bbb.cccProtocol://dataUrl=ShareKey#text
DEBUG expoShareIntent[scheme] from expoConfig: com.aaa.bbb.ccc

code that is not showing incoming share text:

   React.useEffect ( () => {
         // loop forever
         
         if ( shareIntent.text ) {
             Alert ( 'text', shareIntent.text );
         }
         
         if ( shareIntent.webUrl ) {
             Alert ( 'weburl', shareIntent.webUrl );
         }
         
         if ( shareIntent.files ) {
             Alert ( 'files', JSON.stringify( shareIntent.files ) );
         }
                      
     }, [hasShareIntent] );
     
     
     React.useEffect ( () => {
         // loop forever
         
         if ( shareIntent.text ) {
             Alert ( 'text', shareIntent.text );
         }
         
         if ( shareIntent.webUrl ) {
             Alert ( 'weburl', shareIntent.webUrl );
         }
         
         if ( shareIntent.files ) {
             Alert ( 'files', JSON.stringify( shareIntent.files ) );
         }
                      
     }, [shareIntent] );

dont know why the console logs appear when I share text into the app but the app CAN NOT get the actual shared content.

**Comment by achorein** [comment]
your scheme is misconfigured, you received on deep link for `com.aaa.bbb.cccProtocol://` instead of `com.aaa.bbb.ccc://`, do you have multi-scheme in your app.json ?

you can try to override scheme in your app : 
```js
    useShareIntent({
      scheme: "com.aaa.bbb.cccProtocol",
    });
```

**Comment by achorein** [comment]
if you changed your app.json don't forget to clean your expo prebuild : `expo prebuild --no-install --clean`

**Comment by geetee24** [comment]
i have a expo.scheme AND a

"infoPlist": {
"CFBundleURLTypes": [
{
"CFBundleURLSchemes": [
"com.aaa.bbb.ccc"
]

Why do i need both?

I need an example for multiple providers BUT not react native navigation
please.

**Comment by geetee24** [comment]
what does this command do?

**Comment by geetee24** [comment]
i got the code to work.   However when I share say text from an app into my
app - i see a FLASH of a dialog box that auto disappears before my app
comes up with the shared text.

This flash dialog box is not my code.   It appears to be your code?  Is
it?   How make it not flash up?   See attached pic
![IMG004](https://github.com/achorein/expo-share-intent/assets/6679119/75c15ce5-95ea-4dc0-9dd9-8ce75df5af5f)

**Comment by achorein** [comment]
This dialog box is needed by iOS, we cannot remove it (knowned as share extension view).
The share intent auto-submit the dialog to forward the share intent to the app
