### ISSUE TITLE
want expo share intent to load if platform is mobile  BUT not for platform == web

### ISSUE THREAD

**Issue by geetee24** [achorein/expo-share-intent#80]
how make it not load when running in web?

**Comment by achorein** [comment]
you can use the `disabled` option  like this 
```js
useShareIntent({ disabled:  Platform.OS === 'web' })
```

**Comment by achorein** [comment]
look at this issue to handle dynamic import https://github.com/achorein/expo-share-intent/issues/23

**Comment by geetee24** [comment]
import { useShareIntent } from 'expo-share-intent';

your link does not provide a solution to the import issue on web device

**Comment by achorein** [comment]
The first comment give a solution pour expo go client when in development, is the same for web client.

you can do something like this
```js
let useShareIntent = () => { return {} }
if (Platform.OS !== 'web') {
   // do not use import at top of file
   const ESI = require('expo-share-intent')
   useShareIntent = ESI.useShareIntent;
}
```

**Comment by achorein** [comment]
you can retry with v2.2.0 which fixes the crash when importing share intent from web version (with `disabled: true`).
