### ISSUE TITLE
Can we change bundle identifer for ios extension

### ISSUE THREAD

**Issue by sevketaydogdu** [achorein/expo-share-intent#88]
**Describe the bug**
I am getting an error while creating exampleappidentifier.share-extension on apple. if i could change it like exampleappidentifier.share it works it creates bundle identifer
 

**Environment**
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 119.22 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.2
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.04.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
 
- expo version  : 50
- using firebase : no
- using static build :  no
- routing : expo-router
-  package version (ex: 1.2.0) : 1.7.0
- platform target :  iOS
- device :  real device
- type: local eas build

**Comment by achorein** [comment]
changing `${appIdentifier}.share-extension` to `${appIdentifier}.shareextension` is enough for you ?

**Comment by achorein** [comment]
@sevketaydogdu do you have a way of testing this [PR](https://github.com/achorein/expo-share-intent/pull/117) to make sure it fixes your problem?

**Comment by achorein** [comment]
@sevketaydogdu now available in v2.6.0 and v3.1.0 with `iosShareExtensionBundleIdentifier` parameters 🚀
