### ISSUE TITLE
shareIntent is "null" in case app was not opened before clicking on "Share"

### ISSUE THREAD

**Issue by anton950712** [achorein/expo-share-intent#9]
**Describe the bug**
 In case the app is NOT opened and I'm doing sharing, then the app just opening WITHOUT shareIntent info (Sharing just URL).
 
```
console.log(hasShareIntent, shareIntent, error)
null {"files": null, "text": null} undefined
```

**Additional context**
- expo version : 49
- package version : 0.2.0
- target : Android
- device : simulator and real device
- type : local build and eas build

**Comment by smak021** [comment]
Facing the same issue. It only works for me when the app is in the background (Android).

**Comment by achorein** [comment]
it sounds likes a bug in my kotlin implementation, I will make some tests about that.

**Comment by achorein** [comment]
release `0.2.1` and `1.0.1` resolve the issue
