### ISSUE TITLE
Dimensions of images captured with iOS camera are swapped when shared.

### ISSUE THREAD

**Issue by usmansbk** [achorein/expo-share-intent#95]
**Describe the bug**
The `width` and `height` of images taken with an iOS camera and shared with the app are swapped.

`expo-share-intent` loads the image with the following data:
```js
{"fileName": "IMG_5171-60E60263-F351-48E0-9076-916795F9919F.JPG", "height": 3024, "mimeType": "image/jpeg", "path": "file:///Users/usman/Library/Developer/CoreSimulator/Devices/446D1C8A-D7E8-48CB-BB37-C95818F8E990/data/Containers/Shared/AppGroup/1F1E0A8A-620C-4E7B-9E0E-65E759BD59B0/020FB1AD-D0EA-4C34-A60A-FFB708CA6CD0.JPG", "size": 2057210, "width": 4032}
```
You can see `width` is `4032` and `height` is `3024`.

while `expo-image-picker` loads the same image as:

```js
{"assetId": "50728FCF-30B5-49F8-B6CA-22E7A043B325/L0/001", "base64": null, "duration": null, "exif": null, "fileName": "IMG_5171-60E60263-F351-48E0-9076-916795F9919F.jpg", "fileSize": 399112, "height": 4032, "mimeType": "image/jpeg", "type": "image", "uri": "file:///Users/usman/Library/Developer/CoreSimulator/Devices/446D1C8A-D7E8-48CB-BB37-C95818F8E990/data/Containers/Data/Application/F0823413-A76C-4D07-BEE4-64B38632B550/Library/Caches/ImagePicker/7D70D411-45DE-45FC-BD95-BEA3783A2FD2.jpg", "width": 3024}
```

Here you can see `width` is `3024` and `height` is `4032`.

Here is a sample image file:
[https://github.com/user-attachments/assets/495a7ede-f837-4f25-a855-1f34a99824ff](https://github.com/user-attachments/assets/495a7ede-f837-4f25-a855-1f34a99824ff)

**To Reproduce**
- Take a photo with an iOS camera.
- Share photo
- notice how width and height are swapped for unknown reasons.

**Environment**
System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 79.06 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/usman/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11842104
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/usman/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Additional context**

- expo version (ex: 49) : 51
- using firebase : yes
- using static build : yes / no
- routing :  react-navigation
- package version (ex: 1.2.0) : 2.3.0
- platform target :  iOS 16.4
- device : simulator
- type: expo eas build

**Comment by achorein** [comment]
available in v2.3.1
