### ISSUE TITLE
[iOS] cannot share .txt file

### ISSUE THREAD

**Issue by QuocTA-Amela** [achorein/expo-share-intent#98]
**Describe the bug**
I share a .txt file from another app. My Expo app is shown on the option list, but my Expo app did not get any data of that .txt file.
However, I tried the images file (png) and it worked.

**To Reproduce**
Share a .txt file from another app.

**Environment**
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 100.92 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.4
    path: ~/.nvm/versions/node/v18.20.4/bin/node
  Yarn:
    version: 1.22.18
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.6.4
    path: ~/.nvm/versions/node/v18.20.4/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: ^18.3.1
  react-native:
    installed: 0.74.5
    wanted: ^0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Additional context**
This is with image.
<img width="308" alt="image" src="https://github.com/user-attachments/assets/25d0b2ca-08ea-4f2b-859e-501aa51e9123">
<img width="298" alt="image" src="https://github.com/user-attachments/assets/06fab2f2-e2c0-4f42-8375-198ca0e7cee5">
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/8d82896c-c760-4f24-9d94-4af5dee677e4">

This is with text.
<img width="302" alt="image" src="https://github.com/user-attachments/assets/7296f62d-0029-414d-86ef-e5a41b521a5f">
<img width="301" alt="image" src="https://github.com/user-attachments/assets/6c7a4f21-ac81-4cdd-889a-673fc23a106e">
<img width="1295" alt="image" src="https://github.com/user-attachments/assets/a5a26cfe-ce03-40ff-bc70-1ba3d82586a9">

My app.json
<img width="528" alt="image" src="https://github.com/user-attachments/assets/65d583a3-59f9-402d-9b7b-86bc4be3b009">

- expo version (ex: 49) : 51
- using firebase : no
- using static build : no
- routing : (ex: basic / expo-router / react-navigation): expo-router
- package version (ex: 1.2.0) : 2.3.0
- platform target : Android 
- device : simulator
- type: expo build (npx expo run:android)

**Comment by QuocTA-Amela** [comment]
It also happened in iOS too. 
![image](https://github.com/user-attachments/assets/8e90b67d-b184-48ce-8e6b-191e2eb06c12)

@achorein

**Comment by Nantris** [comment]
Are you testing this with a custom dev client? I didn't think a custom dev client could receive intents.

That said, I'm seeing no data passed to my `.apk` app when I share a URL. Not sure how to debug this.

**Comment by achorein** [comment]
thank you for your feedback, the problem has been identified!

**Comment by achorein** [comment]
available in v2.3.1
